name: Breathe Safari
favicon: null
layout_spectrum: 0.2954
typography_spectrum: 0.9350899173878133
title: Wellness events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9315526878926903
  lightness: 0.08703571232035756
  saturation: 0.242650835076347
  rhythmicContrast: 0.9180595313664526
purpose: []
