title: WELLNESS EVENTS
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.242650835076347
  brandStrength: 0.5
  lightness: 0.25
  brandColors:
    - '#010101'
    - '#FFFFFF'
    - '#3E3636'
    - '#D6AF28'
    - '#CE7444'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
name: Breathe Safari
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.52813
layout_spectrum: 0.19309
