name: Breathe Safari
favicon: null
layout_spectrum: 0.50256
typography_spectrum: 0.9350899173878133
title: WELLNESS EVENTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bb7c5d'
    - '#91472e'
    - '#e0d8d8'
    - '#dc9f83'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.242650835076347
  rhythmicContrast: 0.25
purpose: []
